### PR TITLE
Added en_ud.lang

### PR DESCRIPTION
**Pull request by The-Fireplace**

### CODE REVIEW

**Comment by Tamaized** [comment]
Yes

**Comment by ChloeDawn** [comment]
I approve of this

**Comment by liach** [comment]
oh ud is upside down

**Comment by Kenkron** [comment]
Lol

**Comment by Kenkron** [comment]
If there are no objections, I'll make the base branch 1.11.2, then merge it up to 1.12.2 as well.

**Comment by TehNut** [comment]
I believe he is looking at turning this into a gradle plugin that applies the new lang on build. (https://github.com/mezz/JustEnoughItems/pull/1141#issuecomment-366602853)

**Pull request merged**
