### PR TITLE
Create fr_FR.lang

### PR DESCRIPTION
**Pull request by Mazdallier**

### CODE REVIEW

**Comment by Hunternif** [comment]
Hi, thank you very much for making this translation! I did study some French on my own, but I'm not feeling anywhere near confident enough to make my own translation :Ь
Кight now I'm thinking of changing a line of text and if you have the time, I would like you to translate it for me into French.

The line is: "Follow the player".

It replaces the old "Reset position" line and definitely makes more sense. Also, for future localization needs, if that's alright with you, may I ask for some way of contacting you? Thanks.

**Comment by Hunternif** [comment]
Or maybe just "Follow player". That appears more appropriate. I'm not sure myself.

**Comment by Hunternif** [comment]
And here's a couple more:
"Scale in blocks" - for the tooltip on a scale bar in the bottom left corner
"Village" - for village tooltips

**Comment by Hunternif** [comment]
Okay, I think I got it:

Suivez le joueur
Échelle en blocs
Village

Is that correct?

**Comment by Mazdallier** [comment]
Yes it's correct maybe prefering "Suivre le joueur".
"Suivez le joueur" sound like "can you follow this player ?"

**Comment by Mazdallier** [comment]
A ton service si tu nécessite d'autres traductions. ;)

**Comment by Hunternif** [comment]
I see, thank you. I think I'll need to correct the verb form in other places as well, like in "Ajoutez une marque" and "Exportez une image" it's you asking the GUI to do things not vice versa :)

**Comment by Hunternif** [comment]
I'm having second thoughts about "Dialogue d'ouverture de fichier" as well... I know my own wording was not very clear, but the idea here is that the dialog is being opened, and that process takes some time, at least on my machine.

**Comment by Mazdallier** [comment]
French 'impératif présent' is very complexe, here my explaination : 
Ajoutez is used for a polish formulation to your boss
Ajouter is used to give order for your slaves (used in Windows menu)

You can replace "Dialogue d'ouverture de fichier" with "Ouvrir un fichier..."

**Pull request merged**
