### PR TITLE
Properly mark AAO as a client only mod

### PR DESCRIPTION
**Pull request by TehNut**
As of https://github.com/MinecraftForge/MinecraftForge/commit/7269d2244914700dd5a7970a728bd043132f8746 (Over 2 years ago!), Forge has had a field in the `@Mod` annotation to mark a mod as client only so it does not load on dedicated servers.

This also has the side effect of removing some of the Sysout prints.

### CODE REVIEW

**Comment by liach** [comment]
Not really... The server sometimes syncs configs to the client, such as only display overlay when the item is in hand but not when it is in the player inventory.

**Comment by TehNut** [comment]
There is nothing that does that in the codebase.

**Comment by liach** [comment]
If the main mod handles that, then this pull is great.

**Comment by Kenkron** [comment]
This would have saved me a lot of work if I'd known about it when I first integrated AAO with AA, but all I could find then were warnings about using the `@SideOnly` annotation.

**Comment by Kenkron** [comment]
Works like a charm!

**Pull request merged**
