### PR TITLE
Rewrite configuration system

### PR DESCRIPTION
**Pull request by TehNut**
Switches config systems of both mods to use the new Forge annotation system. Includes in-game configuration GUI.

Minor unmentioned changes:
* Fixes a couple null-stack checks in AAO. They are now `isEmpty()` as they should be. There's a few of these in AA as well.
* Switches the AAO usage of the `jline` logger to a `log4j` logger.

### CODE REVIEW

**Comment by Kenkron** [comment]
Note: this also updates forge version

**Comment by TehNut** [comment]
Ah yes. How could I forget that. 

It also sets the minimum Forge version allowed to `13.20.0.2262` which is the version that added Config GUI support to `@Config`. It's newer than the recommended build, but in 1.11, nobody should be sticking to recommended.

**Comment by Kenkron** [comment]
I wasn't complaining, just wanted to mark it down so that others know to re-de-compile.  :)

**Comment by Kenkron** [comment]
When I try running your branch, the overlay doesn't show up. Does this happen on your end? I can try re-re-de-compiling if it isn't.

**Comment by TehNut** [comment]
Whoops, forgot to make the event subscriber static.

**Comment by Kenkron** [comment]
Works! merging.

**Pull request merged**
