### PR TITLE
1.9.4 update

### PR DESCRIPTION
**Pull request by thecodewarrior**
The update isn't ready, but I wanted to make somewhere for discussion about changes.

### CODE REVIEW

**Comment by thecodewarrior** [comment]
@Kenkron How important is keeping the API the same? I'm trying moving away from plain strings as marker types and instead having a registry, that way there can more easily be much more advanced behavior surrounding markers.

**Comment by Kenkron** [comment]
I'm going to look at this when I get back home tomorrow. I figure the API is allowed to change. Also, I added debug as a config option starting at 1.8.9,  id like to add that to the main branch too.

**Comment by Kenkron** [comment]
I'll probably merge the 1.8.9 branch to master, then pull this in.   There will be conflicts, but they shouldn't be too bad.  I can tell on mobile, is this pull request to the main branch, or a separate 1.9.4 branch?

**Comment by thecodewarrior** [comment]
It's into master. 

And now that I think about it I could have the old API method find the `MarkerType` based on the passed string.

**Comment by Kenkron** [comment]
Do you think you could issue this pull request to a new 1.9.4 branch instead?  (I just made one) I know it sounds weird, but I want to send the basic changes of 1.8.9 through the master branch before 1.9.4 so that features don't get accidentally lost from one version to another.  You can pull to the 1.9.4, then I'll merge that to master after 1.8.9 has gone through and fix the merge conflicts.

**Comment by thecodewarrior** [comment]
Sure.

**Pull request closed without merging**
