### PR TITLE
Adds jar signing and signature verification

### PR DESCRIPTION
**Pull request by tyra314**
This adds an optional step into the build process, which will sign the generated jar file. 

More resources:
- https://tutorials.darkhax.net/tutorials/jar_signing/
- https://mcforge.readthedocs.io/en/latest/concepts/jarsigning/

### CODE REVIEW

**Comment by tyra314** [comment]
You can successfully build the mod even without setting up a private key, but the following log messages will appear:

```
[11:12:09] [Client thread/ERROR] [FML]: The mod antiqueatlas is expecting signature @FINGERPRINT@ for source antiqueatlas-1.12.2-4.5.1.jar, however there is no signature matching that description
[11:12:09] [Client thread/WARN] [antiqueatlas]: Invalid fingerprint detected! The file antiqueatlas-1.12.2-4.5.1.jar may have been tampered with. This version will NOT be supported by the author!
[11:12:09] [Client thread/ERROR] [FML]: The mod antiqueatlasoverlay is expecting signature @FINGERPRINT@ for source antiqueatlas-1.12.2-4.5.1.jar, however there is no signature matching that description
[11:12:09] [Client thread/WARN] [antiqueatlasoverlay]: Invalid fingerprint detected! The file antiqueatlas-1.12.2-4.5.1.jar may have been tampered with. This version will NOT be supported by the author!
```

*edit: To be clear, these will show up during the Minecraft start sequence, not during build

**Comment by osipxd** [comment]
Can you also reindent build script with spaces?

**Comment by Hunternif** [comment]
Wow this sounds cool, I will revisit this later

**Comment by tyra314** [comment]
I don't think this is needed anymore.

**Pull request closed without merging**
