### PR TITLE
Marker improvements and massive maps

### PR DESCRIPTION
**Pull request by thecodewarrior**
I've changed the markers from being nothing but a texture to being much more flexible.

##### Multiple icons

You can specify multiple icons at different resolutions, and the mod will select the best one based on the size that it's drawing.

##### Custom size

You can specify the size the markers will render at. The size is represented in tiles.

##### Clipping

You can specify a minimum and maximum zoom level for a marker to render

##### Ignoring hidden markers

You can specify whether the marker should render even if markers are hidden

##### Tile markers

You can specify if a marker should scale with the map or be the same size regardless of zoom

##### Technical markers

You can specify if a marker should be excluded from the marker placing menu

##### Center point

You can specify what point on the marker should be at the marker's actual location

#### JSON format

The JSON config file is called "markers.json"

Here is the format so far:
```
{
    "version": 1,
    "data": {
    	"antiqueatlas:Example": {
		"__comment": [
			"Any of these values can be ommited. The mod will either use the default value or if it is already been registered it will keep the existing values",
			"This example entry is never parsed, and if modified, will not persist"
		],
		"textures": [
			"List of icons at different resolutions",
			"[Default: `antiqueatlas:textures/gui/markers/red_x_small.png`]"
		],
		"size": "[Default: 2] The width and height of the marker, in tiles (a chunk at 1x zoom)", 
		"clipMin": "[Default: -1000] The minimum zoom, -1 is 1/2x, -2 is 1/4x, ...",
		"clipMax": "[Default:  1000] The maximum zoom, 0 is 1x, 1 is 2x, ...",
		"alwaysShow": "[Default: false] True if the marker should appear regardless of whether hide markers is on",
		"isTile": "[Default: false] True if the marker should scale with the map",
		"isTechnical": "[Default: false] True if user should not be able to place the marker on the map",
		"centerX": "[Default: 0.5] The point in the image that should be at the location of the marker (0-1)",
		"centerY": "[Default: 0.5] The point in the image that should be at the location of the marker (0-1)"
	}
    }
}
```

The example is added to the beginning of the list each time the file is generated, and ignored when the file is loaded. Any registered markers will be added to the file as blank objects, and blank objects will be deleted when saved.

It also adds support for exporting the new advanced markers and for exporting massive maps to images by exporting the image in strips (though this does make the process much slower as it has to re-render the image several times.) It makes the progress bar actually reflect progress, and adds a small progress bar in the bottom-right corner so if you exit the GUI while exporting you'll know what it's doing.

[Here](http://imgur.com/0SJ6QWY) is an example of the size of images you can export now, this one is almost 20k by 20k pixels. All with only ~2gb of ram allocated to minecraft.

### CODE REVIEW

**Comment by Kenkron** [comment]
This is super cool, but I've only just finished merging 1.8.9's GLStateManager calls into 1.9.4 (without them, the map turns blue if the chat box is on the screen), and now there are merge conflicts.

**Comment by thecodewarrior** [comment]
I'll get on that as soon as I can.

Working on this is too fun. I must remember that I have other mods that people want updated. :P

**Comment by Kenkron** [comment]
If you want, you can merge with a new MarkerRegistry branch, and I'll work out the conflicts.

**Comment by thecodewarrior** [comment]
If you want to do it you can, it'll be at least an hour before I can sit down and resolve the conflicts, so if you're willing to wait I can do it.

**Comment by thecodewarrior** [comment]
Turns out I have time now. I'm almost done.

**Comment by Kenkron** [comment]
that was fast

**Comment by thecodewarrior** [comment]
It was only like a dozen lines. Most of which were moving over two GlStateManager calls and deleting the old code.

**Comment by thecodewarrior** [comment]
Well, that merged into master. Not sure that's what was supposed to happen. :/

**Comment by Kenkron** [comment]
Actually, that's the merge from the first 1.9.4 version you put in.  I'll merge over this commit as soon as eclipse stops crashing and I can get a good test running.  Do you know how to start minecraft from terminal in a dev environment?

**Comment by thecodewarrior** [comment]
Nope. We also need to figure out how to get the file picker working reliably.

**Pull request merged**
