### PR TITLE
Adds marker on player position

### LINKED ISSUE #63: Add waypoint on player position and with precise coordinates
* Add a "add waypoint on own position" button
* Provide a window to let the user enter precise waypoint coordinates
  * or show them in an overlay while the map is in "waypoint place mode".

### PR DESCRIPTION
**Pull request by tyra314**
While pressing the shift key, a click to "Add marker" will create a new
marker on the position of the player.

This partly fixes #63. I don't think that a precise input is in the spirit of the mod.

### CODE REVIEW

**Comment by TehNut** [comment]
Dunno if it's just Github's view, but that diff is really messed up.

It looks like a formatting change, however [the actual PR content](https://github.com/AntiqueAtlasTeam/AntiqueAtlas/pull/208/files#diff-d3424431c7bc73ee2c54634d3a447d62R291) is using inconsistent formatting.

**Comment by tyra314** [comment]
Dammit, auto format hit me hard :( I'll fix that

**Comment by tyra314** [comment]
I see what the problem was, the file is actually *partly* indented with spaces instead of tabs like the other files ¯\\\_(ツ)_/¯

**Comment by Hunternif** [comment]
Woah this is cool, I've completely forgoten about it.

**Pull request merged**
