### PR TITLE
Create zh_CN.lang

### PR DESCRIPTION
**Pull request by crafteverywhere**

### CODE REVIEW

**Comment by Hunternif** [comment]
Hi, thank you very much for making this translation! I'm sorry I took so long to respond. Right now I'm thinking of changing a line of text and if you have the time, I would like you to translate it for me into Chinese.

The line is: "Follow the player".

It replaces the old "Reset position" line and definitely makes more sense. Also, for future localization needs, if that's alright with you, may I ask for some way of contacting you? Thanks.

**Comment by crafteverywhere** [comment]
It's "跟随该玩家" in Chinese. 
And my email address is craftmanlu@foxmail.com.

**Comment by Hunternif** [comment]
And here's a couple more:
"Scale in blocks" - for the tooltip on a scale bar in the bottom left corner
"Village" - for village tooltips

**Comment by crafteverywhere** [comment]
"Scale in blocks" - "以方块缩放";
"Village" - "村庄" .

**Comment by Hunternif** [comment]
Thank you!

**Comment by crafteverywhere** [comment]
You're welcome, and feel free to call me if you need any help with this.XD

**Comment by Hunternif** [comment]
Actually I find this page here a rather comfortable form of communication :Ь
So here's another line: "Delete marker"

**Comment by crafteverywhere** [comment]
XD, It's "删除标记".

**Comment by Hunternif** [comment]
Hi! I added another line :) Please translate it and make a pull request, if that's okay.

**Pull request merged**
